apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deployment
spec:
  selector:
    matchLabels:
      app: devops-project
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: devops-project
    spec:
      containers:
      - name: devops-project
        image: ahmedsamymahrous/devops-project-image
        imagePullPolicy: Always
        ports:
        - containerPort: 8080